// import figmaSvg from '../images/svg/figma.svg';
// import adobeSvg from '../images/svg/adobeXd.svg';
// import inVisionSvg from '../images/svg/inVision.svg';
import npcCalculatorImg from '../images/on-home-page/npc_calculator.png';
import armyCostImg from '../images/on-home-page/army_cost.png';
import resourcesManagerImg from '../images/on-home-page/resources_manager.png';
export interface mainNavProps {
	name: string;
	route: string;
	show: boolean;
	icon?: string;
}

export const mainNav: mainNavProps[] = [{
	name: 'Home',
	route: '/',
	show: true,
	icon: 'home',
}, {
	name: 'About',
	route: '/about',
	show: true,
	icon: 'about',
}, {
	name: 'Tools',
	route: '/tools',
	show: true,
	icon: 'tools',
}, {
	name: 'Contact',
	route: '/contact',
	show: true,
	icon: 'contact',
}, {
	name: 'Dashboard',
	route: '/dashboard',
	show: false,
	icon: 'admin',
}];

export interface homeInfoCardsProps {
	title: string;
	title_color: string;
	subtitle: string;
	description: string;
}

export const HOME_INFO_CARDS: homeInfoCardsProps[] = [
	{
		title: '5',
		title_color: 'medium_blue',
		subtitle: 'Total Tools',
		description: 'Lot of tools that offer free and premium features',
	},{
		title: '5',
		title_color: 'medium_green',
		subtitle: 'Free Tools',
		description: 'Explore free tools that would help you achieve something',
	},{
		title: '0',
		title_color: 'medium_red',
		subtitle: 'Premium Tools',
		description: 'Need more feature? lets try the premium tools',
	},
];

export interface cardsProps {
	image: string;
	title: string;
	description: string;
	info: string;
	info_color: string;
	button_1: string;
	button_2?: string;
}

export const HOME_CARDS: cardsProps[] = [
	{
		image: npcCalculatorImg,
		title: 'Npc Calculator',
		description: 'With the help of this tool, you can calculate exactly how many resources you need to build a resource or... ',
		info: 'Free',
		info_color: 'small_green',
		button_1: 'Try it now!',
	},{
		image: armyCostImg,
		title: 'Army Cost',
		description: 'This tool will help you calculate how much the troops will cost, what attack or defense power they have. Also...',
		info: 'Free',
		info_color: 'small_green',
		button_1: 'Try it now!',
	},{
		image: resourcesManagerImg,
		title: 'Resources Manager',
		description: `The resources manager is very useful when the number of your villages increases. With this tool you will be...`,
		info: 'Free',
		info_color: 'small_green',
		button_1: 'Try it now!',
	}
];

export interface FooterLink {
	name: string;
	link: string;
}
export interface FooterLinks {
	title: string;
	links: FooterLink[];
}

export const FOOTER_LINKS: FooterLinks[] = [
	{	title: 'Resource',
		links: [
			{ name: 'Home', link: '/' },
			{ name: 'About Us', link: '/about' },
			{ name: 'Contact', link: '/contact' },
		],
	}, {	
		title: 'Support Us',
		links: [
			{ name: 'Donate', link: 'https://www.paypal.com/paypalme/cnwstrav' },
		],
	}
];

export const iconList = [
	{ option: 'success' }, 
	{ option: 'copy' }, 
	{ option: 'arrow-up' }, 
	{ option: 'arrow-down' }, 
	{ option: 'home'}, 
	{ option: 'about' }, 
	{ option: 'dashboard' },
	{ option: 'contact' },
	{ option: 'admin' },
	{ option: 'info' },
	{ option: 'google' },
	{ option: 'light-search' },
];

export const countryList =  [
	{ option: 'Afghanistan' },
	{ option: 'Albania' },
	{ option: 'Algeria' },
	{ option: 'American Samoa' },
	{ option: 'Andorra' },
	{ option: 'Angola' },
	{ option: 'Anguilla' },
	{ option: 'Antarctica' },
	{ option: 'Antigua and Barbuda' },
	{ option: 'Argentina' },
	{ option: 'Armenia' },
	{ option: 'Aruba' },
	{ option: 'Australia' },
	{ option: 'Austria' },
	{ option: 'Azerbaijan' },
	{ option: 'Bahamas (the)' },
	{ option: 'Bahrain' },
	{ option: 'Bangladesh' },
	{ option: 'Barbados' },
	{ option: 'Belarus' },
	{ option: 'Belgium' },
	{ option: 'Belize' },
	{ option: 'Benin' },
	{ option: 'Bermuda' },
	{ option: 'Bhutan' },
	{ option: 'Bolivia' },
	{ option: 'Bonaire, Sint Eustatius and Saba' },
	{ option: 'Bosnia and Herzegovina' },
	{ option: 'Botswana' },
	{ option: 'Bouvet Island' },
	{ option: 'Brazil' },
	{ option: 'British Indian Ocean Territory' },
	{ option: 'Brunei Darussalam' },
	{ option: 'Bulgaria' },
	{ option: 'Burkina Faso' },
	{ option: 'Burundi' },
	{ option: 'Cabo Verde' },
	{ option: 'Cambodia' },
	{ option: 'Cameroon' },
	{ option: 'Canada' },
	{ option: 'Cayman Islands' },
	{ option: 'Central African Republic' },
	{ option: 'Chad' },
	{ option: 'Chile' },
	{ option: 'China' },
	{ option: 'Christmas Island' },
	{ option: 'Cocos (Keeling) Islands' },
	{ option: 'Colombia' },
	{ option: 'Comoros (the)' },
	{ option: 'Congo (the Democratic Republic)' },
	{ option: 'Congo' },
	{ option: 'Cook Islands' },
	{ option: 'Costa Rica' },
	{ option: 'Croatia' },
	{ option: 'Cuba' },
	{ option: 'Curaçao' },
	{ option: 'Cyprus' },
	{ option: 'Czechia' },
	{ option: `Côte d'Ivoire` },
	{ option: 'Denmark' },
	{ option: 'Djibouti' },
	{ option: 'Dominica' },
	{ option: 'Dominican Republic' },
	{ option: 'Ecuador' },
	{ option: 'Egypt' },
	{ option: 'El Salvador' },
	{ option: 'Equatorial Guinea' },
	{ option: 'Eritrea' },
	{ option: 'Estonia' },
	{ option: 'Eswatini' },
	{ option: 'Ethiopia' },
	{ option: 'Falkland Islands [Malvinas]' },
	{ option: 'Faroe Islands' },
	{ option: 'Fiji' },
	{ option: 'Finland' },
	{ option: 'France' },
	{ option: 'French Guiana' },
	{ option: 'French Polynesia' },
	{ option: 'French Southern Territories' },
	{ option: 'Gabon' },
	{ option: 'Gambia' },
	{ option: 'Georgia' },
	{ option: 'Germany' },
	{ option: 'Ghana' },
	{ option: 'Gibraltar' },
	{ option: 'Greece' },
	{ option: 'Greenland' },
	{ option: 'Grenada' },
	{ option: 'Guadeloupe' },
	{ option: 'Guam' },
	{ option: 'Guatemala' },
	{ option: 'Guernsey' },
	{ option: 'Guinea' },
	{ option: 'Guinea-Bissau' },
	{ option: 'Guyana' },
	{ option: 'Haiti' },
	{ option: 'Heard Island and McDonald Islands' },
	{ option: 'Holy See' },
	{ option: 'Honduras' },
	{ option: 'Hong Kong' },
	{ option: 'Hungary' },
	{ option: 'Iceland' },
	{ option: 'India' },
	{ option: 'Indonesia' },
	{ option: 'Iran' },
	{ option: 'Iraq' },
	{ option: 'Ireland' },
	{ option: 'Isle of Man' },
	{ option: 'Israel' },
	{ option: 'Italy' },
	{ option: 'Jamaica' },
	{ option: 'Japan' },
	{ option: 'Jersey' },
	{ option: 'Jordan' },
	{ option: 'Kazakhstan' },
	{ option: 'Kenya' },
	{ option: 'Kiribati' },
	{ option: `Korea (the Democratic)` },
	{ option: 'Korea (the Republic)' },
	{ option: 'Kuwait' },
	{ option: 'Kyrgyzstan' },
	{ option: `Lao People's Democratic Republic` },
	{ option: 'Latvia' },
	{ option: 'Lebanon' },
	{ option: 'Lesotho' },
	{ option: 'Liberia' },
	{ option: 'Libya' },
	{ option: 'Liechtenstein' },
	{ option: 'Lithuania' },
	{ option: 'Luxembourg' },
	{ option: 'Macao' },
	{ option: 'Madagascar' },
	{ option: 'Malawi' },
	{ option: 'Malaysia' },
	{ option: 'Maldives' },
	{ option: 'Mali' },
	{ option: 'Malta' },
	{ option: 'Marshall Islands' },
	{ option: 'Martinique' },
	{ option: 'Mauritania' },
	{ option: 'Mauritius' },
	{ option: 'Mayotte' },
	{ option: 'Mexico' },
	{ option: 'Micronesia' },
	{ option: 'Moldova' },
	{ option: 'Monaco' },
	{ option: 'Mongolia' },
	{ option: 'Montenegro' },
	{ option: 'Montserrat' },
	{ option: 'Morocco' },
	{ option: 'Mozambique' },
	{ option: 'Myanmar' },
	{ option: 'Namibia' },
	{ option: 'Nauru' },
	{ option: 'Nepal' },
	{ option: 'Netherlands' },
	{ option: 'New Caledonia' },
	{ option: 'New Zealand' },
	{ option: 'Nicaragua' },
	{ option: 'Niger (the)' },
	{ option: 'Nigeria' },
	{ option: 'Niue' },
	{ option: 'Norfolk Island' },
	{ option: 'Northern Mariana Islands' },
	{ option: 'Norway' },
	{ option: 'Oman' },
	{ option: 'Pakistan' },
	{ option: 'Palau' },
	{ option: 'Palestine' },
	{ option: 'Panama' },
	{ option: 'Papua New Guinea' },
	{ option: 'Paraguay' },
	{ option: 'Peru' },
	{ option: 'Philippines' },
	{ option: 'Pitcairn' },
	{ option: 'Poland' },
	{ option: 'Portugal' },
	{ option: 'Puerto Rico' },
	{ option: 'Qatar' },
	{ option: 'Republic of North Macedonia' },
	{ option: 'Romania' },
	{ option: 'Russian Federation' },
	{ option: 'Rwanda' },
	{ option: 'Réunion' },
	{ option: 'Saint Barthélemy' },
	{ option: 'Saint Helena, Ascension and Tristan da Cunha' },
	{ option: 'Saint Kitts and Nevis' },
	{ option: 'Saint Lucia' },
	{ option: 'Saint Martin (French part)' },
	{ option: 'Saint Pierre and Miquelon' },
	{ option: 'Saint Vincent and the Grenadines' },
	{ option: 'Samoa' },
	{ option: 'San Marino' },
	{ option: 'Sao Tome and Principe' },
	{ option: 'Saudi Arabia' },
	{ option: 'Senegal' },
	{ option: 'Serbia' },
	{ option: 'Seychelles' },
	{ option: 'Sierra Leone' },
	{ option: 'Singapore' },
	{ option: 'Sint Maarten (Dutch part)' },
	{ option: 'Slovakia' },
	{ option: 'Slovenia' },
	{ option: 'Solomon Islands' },
	{ option: 'Somalia' },
	{ option: 'South Africa' },
	{ option: 'South Georgia and the South Sandwich Islands' },
	{ option: 'South Sudan' },
	{ option: 'Spain' },
	{ option: 'Sri Lanka' },
	{ option: 'Sudan' },
	{ option: 'Suriname' },
	{ option: 'Svalbard and Jan Mayen' },
	{ option: 'Sweden' },
	{ option: 'Switzerland' },
	{ option: 'Syrian Arab Republic' },
	{ option: 'Taiwan' },
	{ option: 'Tajikistan' },
	{ option: 'Tanzania, United Republic of' },
	{ option: 'Thailand' },
	{ option: 'Timor-Leste' },
	{ option: 'Togo' },
	{ option: 'Tokelau' },
	{ option: 'Tonga' },
	{ option: 'Trinidad and Tobago' },
	{ option: 'Tunisia' },
	{ option: 'Turkey' },
	{ option: 'Turkmenistan' },
	{ option: 'Turks and Caicos Islands' },
	{ option: 'Tuvalu' },
	{ option: 'Uganda' },
	{ option: 'Ukraine' },
	{ option: 'United Arab Emirates' },
	{ option: 'United Kingdom' },
	{ option: 'United States Minor Outlying Islands' },
	{ option: 'United States of America' },
	{ option: 'Uruguay' },
	{ option: 'Uzbekistan' },
	{ option: 'Vanuatu' },
	{ option: 'Venezuela (Bolivarian Republic of)' },
	{ option: 'Viet Nam' },
	{ option: 'Virgin Islands (British)' },
	{ option: 'Virgin Islands (U.S.)' },
	{ option: 'Wallis and Futuna' },
	{ option: 'Western Sahara' },
	{ option: 'Yemen' },
	{ option: 'Zambia' },
	{ option: 'Zimbabwe' },
	{ option: 'Åland Islands' }
];